# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\userC\Documents\GitHub\Manipulator\Resources\ui\measure-tool-docked-v1.9e-highdpi.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(280, 339)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/Caliper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DockWidget.setWindowIcon(icon)
        DockWidget.setToolTip("Measure Tools")
        DockWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        DockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        DockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        DockWidget.setWindowTitle("Measure Tools")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Label = QtWidgets.QLabel(self.dockWidgetContents)
        self.Label.setToolTip("Measure Tools\n"
"Click on Measure button\n"
"to start measuring")
        self.Label.setText("<b>Click</b> action")
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 0, 4, 1, 1)
        self.dock_float = QtWidgets.QPushButton(self.dockWidgetContents)
        self.dock_float.setMaximumSize(QtCore.QSize(28, 28))
        self.dock_float.setToolTip("un-dock (floating)")
        self.dock_float.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/un_dock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dock_float.setIcon(icon1)
        self.dock_float.setIconSize(QtCore.QSize(24, 24))
        self.dock_float.setObjectName("dock_float")
        self.gridLayout.addWidget(self.dock_float, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.dock_minimize = QtWidgets.QPushButton(self.dockWidgetContents)
        self.dock_minimize.setMaximumSize(QtCore.QSize(28, 28))
        self.dock_minimize.setToolTip("minimize")
        self.dock_minimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dock_minimize.setIcon(icon2)
        self.dock_minimize.setIconSize(QtCore.QSize(24, 24))
        self.dock_minimize.setObjectName("dock_minimize")
        self.gridLayout.addWidget(self.dock_minimize, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.close = QtWidgets.QPushButton(self.dockWidgetContents)
        self.close.setMaximumSize(QtCore.QSize(28, 28))
        self.close.setToolTip("close")
        self.close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/closeW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon3)
        self.close.setIconSize(QtCore.QSize(24, 24))
        self.close.setObjectName("close")
        self.gridLayout.addWidget(self.close, 0, 3, 1, 1)
        self.Help_Caliper = QtWidgets.QPushButton(self.dockWidgetContents)
        self.Help_Caliper.setMinimumSize(QtCore.QSize(0, 0))
        self.Help_Caliper.setMaximumSize(QtCore.QSize(28, 28))
        self.Help_Caliper.setToolTip("Help on Caliper")
        self.Help_Caliper.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help_Caliper.setIcon(icon4)
        self.Help_Caliper.setIconSize(QtCore.QSize(24, 24))
        self.Help_Caliper.setCheckable(False)
        self.Help_Caliper.setChecked(False)
        self.Help_Caliper.setObjectName("Help_Caliper")
        self.gridLayout.addWidget(self.Help_Caliper, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.Controls_Group = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.Controls_Group.setToolTip("Controls")
        self.Controls_Group.setTitle("Controls")
        self.Controls_Group.setObjectName("Controls_Group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Controls_Group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_8.setSpacing(2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 3, 1, 1)
        self.DimensionP2 = QtWidgets.QPushButton(self.Controls_Group)
        self.DimensionP2.setEnabled(False)
        self.DimensionP2.setMinimumSize(QtCore.QSize(32, 48))
        self.DimensionP2.setMaximumSize(QtCore.QSize(48, 48))
        self.DimensionP2.setToolTip("Second Element")
        self.DimensionP2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/DimensionP2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DimensionP2.setIcon(icon5)
        self.DimensionP2.setIconSize(QtCore.QSize(32, 32))
        self.DimensionP2.setCheckable(False)
        self.DimensionP2.setChecked(False)
        self.DimensionP2.setObjectName("DimensionP2")
        self.gridLayout_8.addWidget(self.DimensionP2, 1, 1, 1, 1)
        self.bLabel = QtWidgets.QPushButton(self.Controls_Group)
        self.bLabel.setEnabled(False)
        self.bLabel.setMinimumSize(QtCore.QSize(32, 32))
        self.bLabel.setMaximumSize(QtCore.QSize(32, 32))
        self.bLabel.setToolTip("<html><head/><body><p>Enable extra Label</p><p>for dimensioning</p></body></html>")
        self.bLabel.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/label-d-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bLabel.setIcon(icon6)
        self.bLabel.setIconSize(QtCore.QSize(20, 20))
        self.bLabel.setCheckable(False)
        self.bLabel.setChecked(False)
        self.bLabel.setObjectName("bLabel")
        self.gridLayout_8.addWidget(self.bLabel, 0, 2, 1, 1)
        self.APlane = QtWidgets.QPushButton(self.Controls_Group)
        self.APlane.setEnabled(False)
        self.APlane.setMinimumSize(QtCore.QSize(32, 48))
        self.APlane.setMaximumSize(QtCore.QSize(48, 48))
        self.APlane.setToolTip("Annotation Plane")
        self.APlane.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/AnnPlane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.APlane.setIcon(icon7)
        self.APlane.setIconSize(QtCore.QSize(32, 32))
        self.APlane.setCheckable(False)
        self.APlane.setChecked(False)
        self.APlane.setObjectName("APlane")
        self.gridLayout_8.addWidget(self.APlane, 1, 2, 1, 1)
        self.Measure = QtWidgets.QPushButton(self.Controls_Group)
        self.Measure.setMinimumSize(QtCore.QSize(32, 48))
        self.Measure.setMaximumSize(QtCore.QSize(48, 48))
        self.Measure.setToolTip("Measure Button\n"
"Click Measure to start measuring")
        self.Measure.setText("")
        self.Measure.setIcon(icon)
        self.Measure.setIconSize(QtCore.QSize(32, 32))
        self.Measure.setCheckable(True)
        self.Measure.setChecked(False)
        self.Measure.setObjectName("Measure")
        self.gridLayout_8.addWidget(self.Measure, 0, 0, 1, 1)
        self.DimensionP3 = QtWidgets.QPushButton(self.Controls_Group)
        self.DimensionP3.setEnabled(False)
        self.DimensionP3.setMinimumSize(QtCore.QSize(32, 48))
        self.DimensionP3.setMaximumSize(QtCore.QSize(48, 48))
        self.DimensionP3.setToolTip("Dimension position")
        self.DimensionP3.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/DimensionP3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DimensionP3.setIcon(icon8)
        self.DimensionP3.setIconSize(QtCore.QSize(32, 32))
        self.DimensionP3.setCheckable(False)
        self.DimensionP3.setChecked(False)
        self.DimensionP3.setObjectName("DimensionP3")
        self.gridLayout_8.addWidget(self.DimensionP3, 1, 3, 1, 1)
        self.DimensionP1 = QtWidgets.QPushButton(self.Controls_Group)
        self.DimensionP1.setEnabled(False)
        self.DimensionP1.setMinimumSize(QtCore.QSize(32, 48))
        self.DimensionP1.setMaximumSize(QtCore.QSize(48, 48))
        self.DimensionP1.setToolTip("First Element")
        self.DimensionP1.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/DimensionP1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DimensionP1.setIcon(icon9)
        self.DimensionP1.setIconSize(QtCore.QSize(32, 32))
        self.DimensionP1.setCheckable(False)
        self.DimensionP1.setChecked(False)
        self.DimensionP1.setObjectName("DimensionP1")
        self.gridLayout_8.addWidget(self.DimensionP1, 1, 0, 1, 1)
        self.CleanDist = QtWidgets.QPushButton(self.Controls_Group)
        self.CleanDist.setMinimumSize(QtCore.QSize(32, 48))
        self.CleanDist.setMaximumSize(QtCore.QSize(48, 48))
        self.CleanDist.setToolTip("Clean Measures")
        self.CleanDist.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/Clean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CleanDist.setIcon(icon10)
        self.CleanDist.setIconSize(QtCore.QSize(32, 32))
        self.CleanDist.setCheckable(True)
        self.CleanDist.setChecked(False)
        self.CleanDist.setObjectName("CleanDist")
        self.gridLayout_8.addWidget(self.CleanDist, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 1, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_8, 0, 0, 1, 7)
        self.rbRadius = QtWidgets.QRadioButton(self.Controls_Group)
        self.rbRadius.setMinimumSize(QtCore.QSize(64, 32))
        self.rbRadius.setToolTip("Get Radius of Arc or Circle")
        self.rbRadius.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/Radius.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbRadius.setIcon(icon11)
        self.rbRadius.setIconSize(QtCore.QSize(28, 28))
        self.rbRadius.setChecked(False)
        self.rbRadius.setObjectName("rbRadius")
        self.gridLayout_2.addWidget(self.rbRadius, 3, 0, 1, 1)
        self.rbSnap = QtWidgets.QRadioButton(self.Controls_Group)
        self.rbSnap.setMinimumSize(QtCore.QSize(72, 32))
        self.rbSnap.setToolTip("Snap to EndPoint, MiddlePoint, Center")
        self.rbSnap.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/Snap_Opt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbSnap.setIcon(icon12)
        self.rbSnap.setIconSize(QtCore.QSize(78, 26))
        self.rbSnap.setChecked(True)
        self.rbSnap.setObjectName("rbSnap")
        self.gridLayout_2.addWidget(self.rbSnap, 1, 0, 1, 2)
        self.rbMass = QtWidgets.QRadioButton(self.Controls_Group)
        self.rbMass.setMinimumSize(QtCore.QSize(56, 32))
        self.rbMass.setToolTip("Center of Mass")
        self.rbMass.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/CenterOfMass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbMass.setIcon(icon13)
        self.rbMass.setIconSize(QtCore.QSize(28, 28))
        self.rbMass.setChecked(False)
        self.rbMass.setObjectName("rbMass")
        self.gridLayout_2.addWidget(self.rbMass, 2, 1, 1, 1)
        self.rbLength = QtWidgets.QRadioButton(self.Controls_Group)
        self.rbLength.setMinimumSize(QtCore.QSize(64, 32))
        self.rbLength.setToolTip("Get Length of Edge")
        self.rbLength.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/Length.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbLength.setIcon(icon14)
        self.rbLength.setIconSize(QtCore.QSize(32, 32))
        self.rbLength.setChecked(False)
        self.rbLength.setObjectName("rbLength")
        self.gridLayout_2.addWidget(self.rbLength, 3, 1, 1, 2)
        self.rbAngle = QtWidgets.QRadioButton(self.Controls_Group)
        self.rbAngle.setMinimumSize(QtCore.QSize(64, 32))
        self.rbAngle.setToolTip("Get Angle")
        self.rbAngle.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/Angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbAngle.setIcon(icon15)
        self.rbAngle.setIconSize(QtCore.QSize(32, 32))
        self.rbAngle.setChecked(False)
        self.rbAngle.setObjectName("rbAngle")
        self.gridLayout_2.addWidget(self.rbAngle, 3, 3, 1, 2)
        self.rbBbox = QtWidgets.QRadioButton(self.Controls_Group)
        self.rbBbox.setMinimumSize(QtCore.QSize(56, 32))
        self.rbBbox.setToolTip("Center of BoundingBox")
        self.rbBbox.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("C:\\Users\\userC\\Documents\\GitHub\\Manipulator\\Resources\\ui\\../Documents/GitHub/Manipulator-f3nix/Resources/ui/CenterBBox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbBbox.setIcon(icon16)
        self.rbBbox.setIconSize(QtCore.QSize(28, 28))
        self.rbBbox.setChecked(False)
        self.rbBbox.setObjectName("rbBbox")
        self.gridLayout_2.addWidget(self.rbBbox, 2, 0, 1, 1)
        self.cbAPlane = QtWidgets.QCheckBox(self.Controls_Group)
        self.cbAPlane.setMinimumSize(QtCore.QSize(32, 0))
        self.cbAPlane.setToolTip("use Annotation Plane\n"
"for Dimension")
        self.cbAPlane.setText("")
        self.cbAPlane.setIcon(icon7)
        self.cbAPlane.setIconSize(QtCore.QSize(32, 32))
        self.cbAPlane.setObjectName("cbAPlane")
        self.gridLayout_2.addWidget(self.cbAPlane, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 3, 6, 1, 1)
        self.gridLayout_3.addWidget(self.Controls_Group, 2, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        DockWidget.setTabOrder(self.dock_float, self.dock_minimize)
        DockWidget.setTabOrder(self.dock_minimize, self.Measure)

    def retranslateUi(self, DockWidget):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DockWidget = QtWidgets.QDockWidget()
    ui = Ui_DockWidget()
    ui.setupUi(DockWidget)
    DockWidget.show()
    sys.exit(app.exec_())
